[package]
edition = '2018'
name = "cargo-crev"
version = "0.4.0"
description = "Scalable, social, Code REView system that we desperately need - Rust/cargo frontend"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/dpc/crev"
homepage = "https://github.com/dpc/crev"
keywords = ["code", "review", "tool", "distributed", "cargo"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "README.md"

[[bin]]
name = "cargo-crev"
path = "src/main.rs"

[dependencies]
failure = "0.1"
quicli = "0.3"
structopt = "0.2"
common_failures = "0.1"
cargo = "0.32"
crev-lib = { path = "../crev-lib", version = "0.4" }
crev-data = { path = "../crev-data", version = "0.4" }
crev-common = { path = "../crev-common", version = "0.4" }
semver = "0.9"
default = "0.1"
crates_io_api = "0.3"
serde = "1"
serde_json = "1"
dirs = "1"
atty = "0.2"
term = "0.5"
tokei = "8"
cargo-geiger = { git = "https://github.com/anderejd/cargo-geiger/", rev= "c891bdd10ac84adaf5cc99de9f8efae64ac4e10b" }
walkdir = "*"
resiter = "*"
insideout = "*"
